apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    app: application-pod
  namespace: rappidu-application
spec:
  containers:
    - name: rappidu-application
      image: localhost:5001/rappidu-monolito
      ports:
        - containerPort: 8080