spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: usuario
    password: senha
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
