server:
  servlet:
    context-path: /rappidu

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rappidu.c8p1qodgl3v7.us-east-1.rds.amazonaws.com:3306/rappidu
    username: root
    password: rappidu0808
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
